### ISSUE TITLE
Kuni Yori

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#1916]
![image](https://user-images.githubusercontent.com/31585532/41490746-55799d3c-70ed-11e8-9c08-5122ea5a8276.png)

**Comment by Kwaice** [comment]
Working on it

**Comment by suburbaknght** [comment]
Kuni Yori isn't giving his bonus during Earth Conflicts.

**Comment by jamesoddy** [comment]
@suburbaknght Thanks for the report.  This has recently been fixed in PR #2634 - it just needs merging and applying to the server.

**Comment by MikeyMurray** [comment]
Still not giving his buff during earth conflicts, any new on the fix date?
